### ISSUE TITLE
Allow extra arguments in reqq files.

### ISSUE THREAD

**Issue by sethetter** [sethetter/reqq#2]
So something like `reqq some-request arg1 arg2` works where the args can be referenced in the file somehow.

**Comment by sethetter** [comment]
Maybe a `Vec<&str>` can be passed to `Request#apply_env` containing the arbitrary args, then passed to the handlebars template as an `args` property, then referenced in the template like `args.[0]`, etc.

**Comment by aaronarduino** [comment]
I may be in way over my head with this one but I'd like to give this one a try. I haven't written Rust in a few years so I'm a little Rusty at it haha.

**Comment by sethetter** [comment]
@aaronarduino 😂 🥁 

That's all good! Feel free to push up a draft PR when you have any changes and I'm happy to take a look early in the process if that helps.

I'll be very happy to have this, this is close to the top of my personal list of next features 😄

**Comment by aaronarduino** [comment]
👍 Will do! 

I want to make sure I understand what you are wanting with this feature. Are you wanting these extra args to be included in the http request that is made?

Example: `reqq some-request arg1 arg2` would create the url `<url_base>/someRequest?arg1=something1&arg2=something2`?

Or am I not understanding the feature?

**Comment by sethetter** [comment]
@aaronarduino not quite!

There is an `env` feature that lets you define variables injected into the `.reqq` files.

For this feature, I'm thinking you should be able to pass command line args for other variables that the env files might be missing, or would overwrite them.

`reqq -e test my-request --arg accountId=12345 --arg anotherThing=abcdefg`

Something like that.

I honestly haven't thought about how to implement this, so I hope it's not too complex, lol.

One nice thing is the args can be parsed entirely as strings for now, I wouldn't worry about any other data types.

**Comment by sethetter** [comment]
Something like grabbing all of the args with `--arg`, then parsing them each as `key=value` data, and merging that with the values that were grabbed from the environment file.

**Comment by sethetter** [comment]
Closed by #8 -- thanks @aaronarduino!
